Assignment -1

1.Create a class to represent a Student with attributes like name, age, and grades.
Example Test Case:
○ Input: name = "Alice", age = 20, grades = [90, 85, 88]
○ Output: name: "Alice", age: 20, grades: [90, 85, 88]


In [1]:
class Student:
    def __init__(self, name, age, grades):
        self.name, self.age, self.grades = name, age, grades
    def __str__(self):
        return f"name: \"{self.name}\", age: {self.age}, grades: {self.grades}"

print(Student("Alice", 20, [90, 85, 88]))


name: "Alice", age: 20, grades: [90, 85, 88]


2.Given a CSV file with employee details (name, position, salary), create a class to
represent an Employee.
Example Test Case:
○ Input: CSV file content = [["John Doe", "Manager", 75000],
["Jane Smith", "Engineer", 80000]]
○ Output: Employee(name="John Doe", position="Manager",
salary=75000), Employee(name="Jane Smith",
position="Engineer", salary=80000)

In [3]:
import csv

class Employee:
    def __init__(self, name, position, salary):
        self.name = name
        self.position = position
        self.salary = salary

    def __str__(self):
        return f"Employee(name=\"{self.name}\", position=\"{self.position}\", salary={self.salary})"

    @staticmethod
    def from_csv(file_content):
        employees = []
        for row in file_content:
            employees.append(Employee(row[0], row[1], row[2]))
        return employees


csv_content = [["John Doe", "Manager", 75000],
               ["Jane Smith", "Engineer", 80000]]

employees = Employee.from_csv(csv_content)
for emp in employees:
    print(emp)


Employee(name="John Doe", position="Manager", salary=75000)
Employee(name="Jane Smith", position="Engineer", salary=80000)


3.Implement a program that simulates a basic bank account using a BankAccount
class.
Example Test Case:
○ Input: account_number = "12345678", initial_balance = 1000
○ Output: account_number: "12345678", balance: 1000

In [4]:
class BankAccount:
    def __init__(self, account_number, initial_balance):
        self.account_number = account_number
        self.balance = initial_balance

    def __str__(self):
        return f"account_number: \"{self.account_number}\", balance: {self.balance}"

account = BankAccount(account_number="12345678", initial_balance=1000)
print(account)


account_number: "12345678", balance: 1000


4.Write a Python program that uses a Rectangle class to calculate the area and
perimeter of a rectangle.
Example Test Case:
○ Input: length = 5, width = 3
○ Output: area: 15, perimeter: 16

In [5]:
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

rectangle = Rectangle(length=5, width=3)
print(f"area: {rectangle.area()}, perimeter: {rectangle.perimeter()}")


area: 15, perimeter: 16


Create a class to represent a Car with attributes like make, model, and year.
Example Test Case:
○ Input: make = "Toyota", model = "Camry", year = 2020
○ Output: make: "Toyota", model: "Camry", year: 2020

In [6]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def __str__(self):
        return f"make: \"{self.make}\", model: \"{self.model}\", year: {self.year}"

car = Car(make="Toyota", model="Camry", year=2020)
print(car)


make: "Toyota", model: "Camry", year: 2020


Given a JSON file with customer data, create a Customer class to store and
manipulate the data.
Example Test Case:
○ Input: JSON file content = {"name": "John Doe", "email":
"john.doe@example.com"}
○ Output: Customer(name="John Doe",
email="john.doe@example.com")


In [7]:
import json

class Customer:
    def __init__(self, name, email):
        self.name = name
        self.email = email

    def __str__(self):
        return f"Customer(name=\"{self.name}\", email=\"{self.email}\")"

    @staticmethod
    def from_json(json_content):
        data = json.loads(json_content)
        return Customer(name=data["name"], email=data["email"])

json_content = '{"name": "John Doe", "email": "john.doe@example.com"}'
customer = Customer.from_json(json_content)
print(customer)


Customer(name="John Doe", email="john.doe@example.com")



Write a program that uses a Person class to keep track of a person's name, age,
and address.
Example Test Case:
○ Input: name = "John Doe", age = 30, address = "123 Main St"
○ Output: name: "John Doe", age: 30, address: "123 Main St

In [8]:
class Person:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address

    def __str__(self):
        return f"name: \"{self.name}\", age: {self.age}, address: \"{self.address}\""

person = Person(name="John Doe", age=30, address="123 Main St")
print(person)


name: "John Doe", age: 30, address: "123 Main St"


8.Implement a program that uses a Circle class to calculate the area and
circumference of multiple circles.
Example Test Case:
○ Input: radius = 4
○ Output: area: 50.27, circumference: 25.13

In [10]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return round(math.pi * (self.radius ** 2), 2)

    def circumference(self):
        return round(2 * math.pi * self.radius, 2)

circle = Circle(radius=4)
print(f"area: {circle.area()}, circumference: {circle.circumference()}")

area: 50.27, circumference: 25.13


Given a CSV file with product details (name, price, quantity), create a Product
class to manage the data.
Example Test Case:
○ Input: CSV file content = [["Laptop", 1000, 5], ["Phone",
500, 10]]
○ Output: Product(name="Laptop", price=1000, quantity=5),
Product(name="Phone", price=500, quantity=10)

In [12]:
class Product:
    def __init__(self, name, price, quantity):
        self.name = name
        self.price = price
        self.quantity = quantity

    def __str__(self):
        return f'Product(name="{self.name}", price={self.price}, quantity={self.quantity})'

csv = [["Laptop", 1000, 5], ["Phone", 500, 10]]
products = [Product(name=item[0], price=item[1], quantity=item[2]) for item in csv]

for product in products:
    print(product)

Product(name="Laptop", price=1000, quantity=5)
Product(name="Phone", price=500, quantity=10)


Create a class to represent a Movie with attributes like title, director, and rating.
Example Test Case:
○ Input: title = "Inception", director = "Christopher Nolan",
rating = 8.8
○ Output: title: "Inception", director: "Christopher Nolan",
rating: 8.8


In [13]:
class Movie:
    def __init__(self, title, director, rating):
        self.title = title
        self.director = director
        self.rating = rating

    def __str__(self):
        return f'title: "{self.title}", director: "{self.director}", rating: {self.rating}'

movie = Movie(title="Inception", director="Christopher Nolan", rating=8.8)
print(movie)

title: "Inception", director: "Christopher Nolan", rating: 8.8


Create a base class Shape with methods to calculate area and perimeter, and
derive classes Circle and Square.
Example Test Case:
○ Input: Circle(radius=4), Square(side=5)
○ Output: Circle area: 50.27, Circle perimeter: 25.13, Square
area: 25, Square perimeter: 20

In [14]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius
    def area(self): return round(math.pi * self.radius ** 2, 2)
    def perimeter(self): return round(2 * math.pi * self.radius, 2)

class Square:
    def __init__(self, side):
        self.side = side
    def area(self): return self.side ** 2
    def perimeter(self): return 4 * self.side

circle = Circle(4)
square = Square(5)

print(f"Circle area: {circle.area()}, Circle perimeter: {circle.perimeter()}")
print(f"Square area: {square.area()}, Square perimeter: {square.perimeter()}")


Circle area: 50.27, Circle perimeter: 25.13
Square area: 25, Square perimeter: 20


Implement a class hierarchy to represent different types of employees (Manager,
Engineer) with their attributes.
Example Test Case:
○ Input: Manager(name="John Doe", department="Sales"),
Engineer(name="Jane Smith", field="Software")
○ Output: Manager: John Doe, Department: Sales, Engineer: Jane
Smith, Field: Software


In [15]:

class Employee:
    def __init__(self, name):
        self.name = name

class Manager(Employee):
    def __init__(self, name, department):
        super().__init__(name)
        self.department = department

    def __str__(self):
        return f"Manager: {self.name}, Department: {self.department}"

class Engineer(Employee):
    def __init__(self, name, field):
        super().__init__(name)
        self.field = field

    def __str__(self):
        return f"Engineer: {self.name}, Field: {self.field}"
    
manager = Manager(name="John Doe", department="Sales")
engineer = Engineer(name="Jane Smith", field="Software")

print(manager)
print(engineer)


Manager: John Doe, Department: Sales
Engineer: Jane Smith, Field: Software


Write a Python program that uses inheritance to represent a hierarchy of shapes
(Triangle, Rectangle, etc.).
Example Test Case:
○ Input: Triangle(base=5, height=3), Rectangle(length=4,
width=2)
○ Output: Triangle area: 7.5, Rectangle area: 8

In [19]:

class Shape:
    def area(self):
        pass

class Triangle(Shape):
    def __init__(self, base, height):
        self.base = base
        self.height = height
    
    def area(self):
        return 0.5 * self.base * self.height

class Rectangle(Shape):
    def __init__(self, length, width):
        self.length = length
        self.width = width
    
    def area(self):
        return self.length * self.width

triangle = Triangle(base=5, height=3)
rectangle = Rectangle(length=4, width=2)

print(f"Triangle area: {triangle.area()}")
print(f"Rectangle area: {rectangle.area()}")


Triangle area: 7.5
Rectangle area: 8


Create a class hierarchy to represent different types of animals (Bird, Fish) with
their own attributes and methods.
Example Test Case:
○ Input: Bird(name="Parrot", can_fly=True),
Fish(name="Goldfish", can_swim=True)
○ Output: Bird: Parrot, Can Fly: True, Fish: Goldfish, Can
Swim: True


In [20]:

class Animal:
    def __init__(self, name):
        self.name = name

class Bird(Animal):
    def __init__(self, name, can_fly):
        super().__init__(name)
        self.can_fly = can_fly

    def __str__(self):
        return f"Bird: {self.name}, Can Fly: {self.can_fly}"

class Fish(Animal):
    def __init__(self, name, can_swim):
        super().__init__(name)
        self.can_swim = can_swim

    def __str__(self):
        return f"Fish: {self.name}, Can Swim: {self.can_swim}"

bird = Bird(name="Parrot", can_fly=True)
fish = Fish(name="Goldfish", can_swim=True)

print(bird)
print(fish)


Bird: Parrot, Can Fly: True
Fish: Goldfish, Can Swim: True


Given a JSON file with product details (name, price, quantity), create a Product
class with encapsulated attributes.
Example Test Case:
○ Input: JSON file content = {"name": "Laptop", "price": 1000,
"quantity": 5}
○ Output: Product(name="Laptop", price=1000, quantity=5)

In [21]:
import json

class Product:
    def __init__(self, name, price, quantity):
        self._name = name        
        self._price = price
        self._quantity = quantity

    @property
    def name(self):
        return self._name

    @property
    def price(self):
        return self._price

    @property
    def quantity(self):
        return self._quantity

    @name.setter
    def name(self, value):
        self._name = value

    @price.setter
    def price(self, value):
        self._price = value

    @quantity.setter
    def quantity(self, value):
        self._quantity = value

    def __str__(self):
        return f'Product(name="{self._name}", price={self._price}, quantity={self._quantity})'

json_data = '{"name": "Laptop", "price": 1000, "quantity": 5}'

product_data = json.loads(json_data)

product = Product(name=product_data["name"], price=product_data["price"], quantity=product_data["quantity"])

print(product)


Product(name="Laptop", price=1000, quantity=5)


Implement a program that uses inheritance to represent a hierarchy of vehicles
(Car, Bike, Truck, etc.).
Example Test Case:
○ Input: Car(make="Toyota", model="Camry"), Bike(make="Yamaha",
model="MT-07")
○ Output: Car: Toyota Camry, Bike: Yamaha MT-07

In [22]:

class Vehicle:
    def __init__(self, make, model):
        self.make = make
        self.model = model

class Car(Vehicle):
    def __str__(self):
        return f"Car: {self.make} {self.model}"

class Bike(Vehicle):
    def __str__(self):
        return f"Bike: {self.make} {self.model}"

class Truck(Vehicle):
    def __str__(self):
        return f"Truck: {self.make} {self.model}"

car = Car(make="Toyota", model="Camry")
bike = Bike(make="Yamaha", model="MT-07")
truck = Truck(make="Ford", model="F-150")

print(car)
print(bike)
print(truck)


Car: Toyota Camry
Bike: Yamaha MT-07
Truck: Ford F-150


Write a Python program that uses encapsulation to protect sensitive information
in a User class.
Example Test Case:
○ Input: User(username="john_doe", password="secure123")
○ Output: username: "john_doe", password: "******"

In [23]:
class User:
    def __init__(self, username, password):
        self.username = username  
        self._password = password  

    
    def get_username(self):
        return self.username
    
    def get_password(self):
        return "******"  

    def set_password(self, password):
        self._password = password

    def __str__(self):
        return f'username: "{self.username}", password: "{self.get_password()}"'

user = User(username="john_doe", password="secure123")

print(user)


username: "john_doe", password: "******"


Assignment-2
Class Definition and Object Instantiation

Create a class Library with attributes like name, address, and a
list of books. Implement methods to add and remove books.
○ Example Test Case:
■ Input: name = "City Library", address = "123 Main St",
books = []
■ Method Calls: add_book("Book1"), add_book("Book2"),
remove_book("Book1")
■ Output: name: "City Library", address: "123 Main St",
books: ["Book2"]


In [25]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

class Library:
    def __init__(self, name, address, books=None):
        self.name = name
        self.address = address
        self.books = books if books is not None else []
    
    def add_book(self, book):
        self.books.append(book)

    def remove_book(self, book):
        if book in self.books:
            self.books.remove(book)

    def display_books(self):
        for book in self.books:
            print(f'name:"{self.name}",address:"{self.address}",{book.title} by {book.author}')

if __name__ == "__main__":
    library = Library("City Library", "123 Main St")
    book1 = Book("Book 1", "Author 1")
    book2 = Book("Book 2", "Author 2")
    library.add_book(book1)
    library.add_book(book2)
    
    library.display_books()

name:"City Library",address:"123 Main St",Book 1 by Author 1
name:"City Library",address:"123 Main St",Book 2 by Author 2


Create a class House with attributes like address, num_rooms, and
price. Implement a method to display the house details.
○ Example Test Case:
■ Input: address = "456 Elm St", num_rooms = 4, price =
350000
■ Method Call: display_details()
■ Output: address: "456 Elm St", num_rooms: 4, price:
350000

In [26]:
class House:
    def __init__(self, address, num_rooms, price):
        self.address = address
        self.num_rooms = num_rooms
        self.price = price

    def display_details(self):
        print(f'address: "{self.address}", num_rooms: {self.num_rooms}, price: {self.price}')

house = House(address="456 Elm St", num_rooms=4, price=350000)


house.display_details()


address: "456 Elm St", num_rooms: 4, price: 350000


. Create a class Book with attributes title, author, and price.
Implement a method discount to apply a discount to the book's
price.
○ Example Test Case:
■ Input: title = "Python 101", author = "John Doe",
price = 29.99
■ Method Call: discount(0.1)
■ Output: title: "Python 101", author: "John Doe",
price: 26.99


In [28]:
class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price

    def discount(self, discount_percentage):
        self.price -= self.price * discount_percentage

    def __str__(self):
        return f'title: "{self.title}", author: "{self.author}", price: {self.price:.2f}'

book = Book(title="Python 101", author="John Doe", price=29.99)

book.discount(0.1)

print(book)


title: "Python 101", author: "John Doe", price: 26.99


Create a class Restaurant with attributes name, cuisine_type, and
rating. Implement a method update_rating to change the
restaurant's rating.
○ Example Test Case:
■ Input: name = "Sushi Place", cuisine_type =
"Japanese", rating = 4.5
■ Method Call: update_rating(4.8)

In [29]:
class Restaurant:
    def __init__(self, name, cuisine_type, rating):
        self.name = name
        self.cuisine_type = cuisine_type
        self.rating = rating

    def update_rating(self, new_rating):
        self.rating = new_rating

    def __str__(self):
        return f'name: "{self.name}", cuisine_type: "{self.cuisine_type}", rating: {self.rating}'
restaurant = Restaurant(name="Sushi Place", cuisine_type="Japanese", rating=4.5)

restaurant.update_rating(4.8)

print(restaurant)


name: "Sushi Place", cuisine_type: "Japanese", rating: 4.8


 Create a class School with a class variable total_students and
instance variables name and students. Implement a method to
enroll students and update the total count.
○ Example Test Case:
■ Input: name = "Greenwood High", students = 300
■ Method Call: enroll_students(50)
■ Output: name: "Greenwood High", students: 350,
total_students: 350

In [30]:
class School:
    total_students = 0

    def __init__(self, name, students):
        self.name = name
        self.students = students
        School.total_students += students

    def enroll_students(self, num_students):
        self.students += num_students
        School.total_students += num_students

    def __str__(self):
        return f'name: "{self.name}", students: {self.students}, total_students: {School.total_students}'

school = School(name="Greenwood High", students=300)

school.enroll_students(50)

print(school)


name: "Greenwood High", students: 350, total_students: 350


 Create a class Company with a class variable industry and
instance variables name and num_employees. Implement a method to
update the number of employees.
○ Example Test Case:
■ Input: name = "TechCorp", num_employees = 200
■ Method Call: update_employees(220)
■ Output: name: "TechCorp", num_employees: 220,
industry: "Technology"

In [31]:
class Company:

    industry = "Technology"

    def __init__(self, name, num_employees):
        self.name = name
        self.num_employees = num_employees

    def update_employees(self, new_num_employees):
        self.num_employees = new_num_employees

    def __str__(self):
        return f'name: "{self.name}", num_employees: {self.num_employees}, industry: "{Company.industry}"'

company = Company(name="TechCorp", num_employees=200)

company.update_employees(220)

print(company)


name: "TechCorp", num_employees: 220, industry: "Technology"


Create a base class Employee with attributes name and salary.
Create a subclass Developer that adds an attribute
programming_language.
○ Example Test Case:
■ Input: name = "Alice", salary = 70000,
programming_language = "Python"
■ Output: name: "Alice", salary: 70000,
programming_language: "Python"

In [32]:

class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

class Developer(Employee):
    def __init__(self, name, salary, programming_language):
        super().__init__(name, salary) 
        self.programming_language = programming_language

    def __str__(self):
        return f'name: "{self.name}", salary: {self.salary}, programming_language: "{self.programming_language}"'

developer = Developer(name="Alice", salary=70000, programming_language="Python")
print(developer)


name: "Alice", salary: 70000, programming_language: "Python"


Create a base class Appliance with a method turn_on. Create a
subclass WashingMachine that overrides the turn_on method.
○ Example Test Case:
■ Input: Appliance.turn_on(),
WashingMachine(model="LG").turn_on()
■ Output: "Appliance is turned on", "Washing Machine LG
is turned on"


In [33]:

class Appliance:
    def turn_on(self):
        print("Appliance is turned on")

class WashingMachine(Appliance):
    def __init__(self, model):
        self.model = model

    def turn_on(self):
        print(f"Washing Machine {self.model} is turned on")

appliance = Appliance()
appliance.turn_on()

washing_machine = WashingMachine(model="LG")
washing_machine.turn_on()


Appliance is turned on
Washing Machine LG is turned on


Create a class PrivateData with private attributes username
and password. Implement methods to get and set these attributes.
○ Example Test Case:
■ Input: username = "user1", password = "pass123"
■ Method Calls: get_username(),
set_password("newpass123"), get_password()
■ Output: username: "user1", password: "newpass123"

In [34]:
class PrivateData:
    def __init__(self, username, password):
        self.__username = username  
        self.__password = password 
    def get_username(self):
        return self.__username

    def set_password(self, new_password):
        self.__password = new_password

    def get_password(self):
        return self.__password

    def __str__(self):
        return f'username: "{self.__username}", password: "{self.__password}"'

private_data = PrivateData(username="user1", password="pass123")

print(f"username: {private_data.get_username()}") 
private_data.set_password("newpass123") 
print(f"password: {private_data.get_password()}")


username: user1
password: newpass123


Create a class Account with private attributes account_number
and balance. Implement methods to deposit and withdraw money.
○ Example Test Case:
■ Input: account_number = "987654321", balance = 5000
■ Method Calls: deposit(1500), withdraw(2000),
get_balance()
■ Output: account_number: "987654321", balance: 4500

In [35]:
class Account:
    def __init__(self, account_number, balance):
        self.__account_number = account_number  
        self.__balance = balance  

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0 and amount <= self.__balance:
            self.__balance -= amount
        else:
            print("Invalid withdrawal amount or insufficient balance.")

    def get_balance(self):
        return self.__balance

    def __str__(self):
        return f'account_number: "{self.__account_number}", balance: {self.__balance}'
    
account = Account(account_number="987654321", balance=5000)

account.deposit(1500)  
account.withdraw(2000) 

print(account)


account_number: "987654321", balance: 4500


Create a class PrivateData with private attributes username
and password. Implement methods to get and set these attributes.
○ Example Test Case:
■ Input: username = "user1", password = "pass123"
■ Method Calls: get_username(),
set_password("newpass123"), get_password()
■ Output: username: "user1", password: "newpass123"

In [36]:
class PrivateData:
    def __init__(self, username, password):
        self.__username = username  
        self.__password = password

    def get_username(self):
        return self.__username

    def set_password(self, new_password):
        self.__password = new_password

    def get_password(self):
        return self.__password

    def __str__(self):
        return f'username: "{self.__username}", password: "{self.__password}"'

private_data = PrivateData(username="user1", password="pass123")

print(f"username: {private_data.get_username()}")  
private_data.set_password("newpass123") 
print(f"password: {private_data.get_password()}")  


username: user1
password: newpass123


Create a class Account with private attributes account_number
and balance. Implement methods to deposit and withdraw money.
○ Example Test Case:
■ Input: account_number = "987654321", balance = 5000
■ Method Calls: deposit(1500), withdraw(2000),
get_balance()
■ Output: account_number: "987654321", balance: 4500

In [37]:
class Account:
    def __init__(self, account_number, balance):
        self.__account_number = account_number  
        self.__balance = balance  

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0 and amount <= self.__balance:
            self.__balance -= amount
        else:
            print("Invalid withdrawal amount or insufficient balance.")

    def get_balance(self):
        return self.__balance

    def __str__(self):
        return f'account_number: "{self.__account_number}", balance: {self.__balance}'
    
account = Account(account_number="987654321", balance=5000)

account.deposit(1500)  
account.withdraw(2000)  

print(account)


account_number: "987654321", balance: 4500


Create a function operate_vehicle that takes a vehicle object
and calls its move method. Create classes Car and Bike that
implement move differently.
○ Example Test Case:
■ Input: Car(model="Toyota").move(),
Bike(model="Yamaha").move()
■ Output: "Toyota is driving", "Yamaha is riding"

In [38]:

class Vehicle:
    def move(self):
        pass  

class Car(Vehicle):
    def __init__(self, model):
        self.model = model

    def move(self):
        print(f"{self.model} is driving")

class Bike(Vehicle):
    def __init__(self, model):
        self.model = model

    def move(self):
        print(f"{self.model} is riding")

def operate_vehicle(vehicle):
    vehicle.move()

car = Car(model="Toyota")
bike = Bike(model="Yamaha")

operate_vehicle(car)  
operate_vehicle(bike) 


Toyota is driving
Yamaha is riding


Create a function operate_device that takes a device object
and calls its operate method. Create classes Laptop and
Smartphone that implement operate differently.
○ Example Test Case:
■ Input: Laptop(model="Dell").operate(),
Smartphone(model="iPhone").operate()
■ Output: "Dell is operating", "iPhone is operating"

In [39]:

class Device:
    def operate(self):
        pass  
class Laptop(Device):
    def __init__(self, model):
        self.model = model

    def operate(self):
        print(f"{self.model} is operating")

class Smartphone(Device):
    def __init__(self, model):
        self.model = model

    def operate(self):
        print(f"{self.model} is operating")

def operate_device(device):
    device.operate()

laptop = Laptop(model="Dell")
smartphone = Smartphone(model="iPhone")

operate_device(laptop)  
operate_device(smartphone) 

Dell is operating
iPhone is operating


Define an abstract class Transport with an abstract method
travel. Create subclasses Bus and Train that implement the travel
method.
○ Example Test Case:
■ Input: Bus(route="10A").travel(),
Train(route="Express").travel()
■ Output: "Bus 10A is traveling", "Train Express is
traveling"

In [40]:
from abc import ABC, abstractmethod
class Transport(ABC):
    @abstractmethod
    def travel(self):
        pass  

class Bus(Transport):
    def __init__(self, route):
        self.route = route

    def travel(self):
        print(f"Bus {self.route} is traveling")

class Train(Transport):
    def __init__(self, route):
        self.route = route

    def travel(self):
        print(f"Train {self.route} is traveling")

bus = Bus(route="10A")
train = Train(route="Express")

bus.travel()  
train.travel()  


Bus 10A is traveling
Train Express is traveling


Define an abstract class Payment with an abstract method
process. Create subclasses CreditCard and PayPal that implement
the process method.
○ Example Test Case:
■ Input: CreditCard(number="1234").process(),
PayPal(account="user@example.com").process()
■ Output: "Processing credit card payment for 1234",
"Processing PayPal payment for user@example.com"

In [41]:
from abc import ABC, abstractmethod

class Payment(ABC):
    @abstractmethod
    def process(self):
        pass  

class CreditCard(Payment):
    def __init__(self, number):
        self.number = number

    def process(self):
        print(f"Processing credit card payment for {self.number}")

class PayPal(Payment):
    def __init__(self, account):
        self.account = account

    def process(self):
        print(f"Processing PayPal payment for {self.account}")

credit_card = CreditCard(number="1234")
paypal = PayPal(account="user@example.com")

credit_card.process()  
paypal.process() 


Processing credit card payment for 1234
Processing PayPal payment for user@example.com
