# Generated by Django 5.1.5 on 2025-01-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ON-GOING', 'On-going'), ('ENDED', 'Ended')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('team', models.ManyToManyField(related_name='projects_team', to='accounts.employee')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_projects', to='accounts.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employees', to='accounts.project'),
        ),
    ]
