# Generated by Django 5.1.5 on 2025-01-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_department_alter_employee_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects_team', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_projects', to='accounts.employee'),
        ),
    ]
